[tool.poetry]
name = "nonebot_plugin_spark_gpt"
version = "0.4.2"
description = "Spark-GPT,将多来源的gpt接入qq及更多平台,使用便捷,管理完善,功能强大"
authors = ["canxin121 <1969730106@qq.com>"]
readme = "README.md"
packages = [{ include = "nonebot_plugin_spark_gpt" }]

[tool.poetry.dependencies]
nonebot-plugin-guild-patch = "^0.2.1"
nonebot-adapter-onebot = { version = "^2.0.0-beta.1", optional = true }
python = "^3.9"
aiofiles = "^23.1.0"
aiohttp = "^3.8.4"
bidict = "^0.22.1"
edgegpt = "^0.2.1"
fastapi = "^0.98.0"
httpx = "^0.24.1"
jinja2 = "^3.1.2"
markdown = "^3.4.3"
playwright = "^1.35.0"
poe-api = "^0.4.6"
pydantic = "^1.10.9"
slack-sdk = "^3.21.3"
uvicorn = "^0.22.0"
python-multipart = "^0.0.6"
[tool.poetry.extras]
onebot = ["nonebot-adapter-onebot"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
