[tool.poetry]
name = "nonebot_plugin_spark_gpt"
version = "0.3.8"
description = "Spark-GPT,将多来源的gpt接入qq及更多平台,使用便捷,管理完善,功能强大"
authors = ["canxin121 <1969730106@qq.com>"]
readme = "README.md"
packages = [{include = "nonebot_plugin_spark_gpt"}]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.0.0-beta.1"
aiofiles = "^23.1.0"
aiohttp = "^3.8.4"
bidict = "^0.22.1"
edgegpt = "^0.10.16"
httpx = "^0.24.0"
imagegen = "^0.2"
jinja2 = "^3.1.2"
markdown = "^3.4.3"
nonebot-plugin-guild-patch = "*"
playwright = "^1.33.0"
pydantic = "^1.10.7"
nonebot-adapter-onebot = { version = "^2.0.0-beta.1", optional = true }
pymdown-extensions = "^9.11"
python-markdown-math = "^0.8"
slack-sdk = "^3.21.3"
poe-api = "^0.3.1"

[tool.poetry.extras]
onebot = ["nonebot-adapter-onebot"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
